FROM ansible/ansible-runner:latest
ENV ANSIBLE_ROLES_PATH ${HOME}/roles

COPY requirements.yml ${HOME}/requirements.yml

RUN ansible-galaxy collection install -r ${HOME}/requirements.yml \
 && chmod -R ug+rwx ${HOME}/.ansible && mkdir ${HOME}/roles

RUN pip3 install ansible-tower-cli kubernetes==11.0.0 openshift

COPY roles/playbookintegrity_runner ${HOME}/roles/playbookintegrity_runner
CMD ["ansible-runner", "--role-skip-facts", "-r", "playbookintegrity_runner", "run", "/runner"]