# permissions for end users to edit playbookintegrities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playbookintegrity-editor-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - playbookintegrities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - playbookintegrities/status
  verbs:
  - get
