# permissions for end users to view playbookintegrities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playbookintegrity-viewer-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - playbookintegrities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - playbookintegrities/status
  verbs:
  - get
